version: '3.8'
services:
  user-management:
    build:
      context: .
      dockerfile: UserManagement/Dockerfile
    ports:
      - "32777:80"
  product-management:
    build:
      context: .
      dockerfile: ProductManagement/Dockerfile
    ports:
      - "32778:80"
